language: node_js
node_js:
- 4.3.2
cache:
  directories:
  - node_modules
before_install:
- npm i -g yarn
- openssl aes-256-cbc -K $encrypted_f470db124daf_key -iv $encrypted_f470db124daf_iv -in deploy_key.enc -out deploy_key -d
after_failure:
- ./update.sh