language: node_js
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "barrett.harber@gmail.com"
node_js:
- 4.3.2
cache: yarn
before_script:
- openssl aes-256-cbc -K $encrypted_f470db124daf_key -iv $encrypted_f470db124daf_iv -in deploy_key.enc -out deploy_key -d
- git config user.name "Travis CI"
- git config user.email "$COMMIT_AUTHOR_EMAIL"
after_success:
- ./merge.sh
after_failure:
- ./update.sh